### ISSUE TITLE
Dependency from sass package

### ISSUE THREAD

**Issue by vadimtsushko** [dart-league/ng2_strap#3]
Readme instructions tell that step 2 (adding sass dependency) is optional, but when I tried without sass dependency I could not move futher.
I believe for end-user of the ng2_strap dependency from sass will be unfortunate complication.
I think it's more OK to use one or another css transformer in application but for end-users of library some option to consume library with minimal dependency chain would be much more preferably.

Specifically for me that just did not work. I installed ruby and sass on Windows10 (Russian). But sass transformer broke with unreadable messages (messages were unreadable due to some sort of character map conversion errors in CLI). After some trials I've temporarily changed some language settings to US-EN in Windows (that by necessity broke other programs) to get gist of these messages. And after rebooting sass transformer started to work. Then I'll get some weird behaviour in WebStorm -- namely never ending skanning of the files to build the index. Probably unrelated to sass, but that project worked before and I was running out of time so I've switched back.

I've noticed too that sass package depend from old unittest and some other old stuff. I guess it could be a problem for a pub version solver in future.

**Comment by vadimtsushko** [comment]
I've just looked at sass package itself - it looks like it would not work in environment without .packages directory. 
https://github.com/EvidentSolutions/dart-sass/issues/1

**Comment by luisvt** [comment]
Sorry, I think I made sass not optional any more let me check

**Comment by luisvt** [comment]
installing sass is not optional anymore
