### ISSUE TITLE
Alert Cross png not loading

### ISSUE THREAD

**Issue by red010b37** [dart-league/ng2_strap#5]
When I try to use the alert with the close button it is looking for a png inside my assets lib and its gets a 404

Not Found: http://localhost:63342/fc-app/web/packages/fc_app/assets/img/icons/noti-cross.png

But I also can seem to find the pngs anywhere in the lib or bootstrap?

**Comment by luisvt** [comment]
could you put a full example?

**Comment by red010b37** [comment]
Im so sorry it was all my fault. 

Also I want to say thank your for creating this for the dart community. I it is a mush have anf I will contribute where I can.

**Comment by red010b37** [comment]
Im so sorry it was all my fault. 

Also I want to say thank your for creating this for the dart community. It is a "must have" and I will contribute where I can.
